version: '3.7'
services:
  jobmanager:
    image: flink:1.17-java11
    container_name: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory

  taskmanager:
    image: flink:1.17-java11
    container_name: taskmanager
    depends_on:
      - jobmanager
    ports:
      - "9250:9249"
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml

  pulsar:
    image: apachepulsar/pulsar:3.0.0
    container_name: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
#      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g -Dpulsar.auth.basic.conf=/pulsar/conf/.htpasswd"
      systemTopicEnabled: "true"
      topicLevelPoliciesEnabled: "true"
      transactionCoordinatorEnabled: "true"
#      - authenticationEnabled=true
#      - authorizationEnabled=true
#      - authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderBasic
#      - superUserRoles=super
#      - brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationBasic
#      - brokerClientAuthenticationParameters={\"userId\":\"super\",\"password\":\"superpass\"}
    command: >
      /bin/bash -c
      " bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
